[tools]
actionlint = "1.7.12"
cosign = "3.0.6"
shellcheck = "0.11.0"
yamllint = "1.38.0"

[env]
REGISTRY = "ghcr.io/clemak27"
IMAGE_TAG = "latest"

## general tasks

[tasks.lint]
run = """
actionlint
shellcheck ./build/*.sh
yamllint .
"""

[tasks.clean]
run = """
rm -rf ./output
"""

## base tasks

[tasks.build-image]
hide = true
description = "build a bootc image"
usage = """
arg "<image>" help="image" {
  choices "dankfedora" "dankydeck" "kinoite"
}
"""
run = """
docker build -t ${REGISTRY}/${usage_image}:${IMAGE_TAG} . -f ./Containerfile.${usage_image}
"""

[tasks.run-vm]
hide = true
description = "run a vm with a bootc image"
usage = """
arg "<image>" help="image" {
  choices "dankfedora" "dankydeck" "kinoite"
}
"""
run = """
mkdir -p ./output
podman run \
    --rm \
    -it \
    --privileged \
    --pull=newer \
    --security-opt label=type:unconfined_t \
    -v ./vm.toml:/config.toml:ro \
    -v ./output:/output \
    -v ~/.local/share/containers/storage:/var/lib/containers/storage \
    quay.io/centos-bootc/bootc-image-builder:latest \
    --in-vm \
    --type qcow2 \
    --use-librepo=True \
    --rootfs btrfs \
    ${REGISTRY}/${usage_image}:${IMAGE_TAG}
qemu-kvm -cpu host -m 8G -device virtio-vga-gl -display gtk,gl=on ./output/qcow2/disk.qcow2
"""

[tasks.run-vm-root]
hide = true
description = "run a vm with a bootc image"
usage = """
arg "<image>" help="image" {
  choices "dankfedora" "dankydeck" "kinoite"
}
"""
run = """
image=${REGISTRY}/${usage_image}:${IMAGE_TAG}
mkdir -p ./output
podman save --format oci-archive --output image.tar $image
sudo podman load --input image.tar
sudo podman run \
    --rm \
    -it \
    --privileged \
    --pull=newer \
    --security-opt label=type:unconfined_t \
    -v ./vm.toml:/config.toml:ro \
    -v ./output:/output \
    -v /var/lib/containers/storage:/var/lib/containers/storage \
    quay.io/centos-bootc/bootc-image-builder:latest \
    --type qcow2 \
    --use-librepo=True \
    --rootfs btrfs \
    $image
sudo chown ${USER}:users -R ./output
qemu-kvm -cpu host -m 8G -device virtio-vga-gl -display gtk,gl=on ./output/qcow2/disk.qcow2
"""

[tasks.build-iso]
hide = true
description = "build a bootable with a bootc image"
usage = """
arg "<image>" help="image" {
  choices "dankfedora" "dankydeck" "kinoite"
}
"""
run = """
image=${REGISTRY}/${usage_image}:${IMAGE_TAG}
mkdir -p ./output
podman save --format oci-archive --output image.tar $image
sudo podman load --input image.tar
sudo podman run \
    --rm \
    -it \
    --privileged \
    --pull=newer \
    --security-opt label=type:unconfined_t \
    -v ./iso.toml:/config.toml:ro \
    -v ./output:/output \
    -v /var/lib/containers/storage:/var/lib/containers/storage \
    quay.io/centos-bootc/bootc-image-builder:latest \
    build \
    --type anaconda-iso \
    --use-librepo=True \
    --rootfs btrfs \
    $image
sudo chown ${USER}:users -R ./output
"""

## dankfedora

[tasks."dankfedora:build-image"]
run = "mise run build-image dankfedora"

[tasks."dankfedora:run-vm"]
depends = "dankfedora:build-image"
run = "mise run run-vm dankfedora"

[tasks."dankfedora:build-iso"]
depends = "dankfedora:build-image"
run = "mise run build-iso dankfedora"

## dankydeck

[tasks."dankydeck:build-image"]
run = "mise run build-image dankydeck"

[tasks."dankydeck:run-vm"]
depends = "dankydeck:build-image"
run = "mise run run-vm-root dankydeck"

[tasks."dankydeck:build-iso"]
depends = "dankydeck:build-image"
run = "mise run build-iso dankydeck"
